In [1]:
#Importing numpy
import numpy as np

In [2]:
#using the random function to get random values and randint to get the numbers as integers
vectors = np.random.randint(0,11, size=5)

In [3]:
print(vectors)

[3 8 5 7 7]


In [5]:
vector2 = np.arange(15,56)

In [6]:
#This prints all numbers ranging from 15 to 55
print(vector2)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [7]:
#This prints all numbers ranging from 15 to 55, excluding 15 and 55. That is, value prints starts from 16 to 54
print(vector2[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [13]:
#Creating a random array with 1000 elements 
myArray = np.random.rand(1000)
print(myArray)

[8.68881924e-01 6.43946513e-02 2.13443229e-01 1.97583463e-01
 7.77767443e-02 9.69918463e-01 9.13324933e-01 2.00298577e-01
 1.41471983e-01 6.79549413e-01 9.30695095e-02 7.60218911e-01
 8.04252716e-02 6.00584099e-03 3.76031287e-01 5.84147328e-01
 4.49164101e-02 7.09453372e-02 8.76453531e-01 1.06409097e-01
 5.88924376e-01 4.45628827e-01 8.50503087e-01 8.88713712e-01
 6.79579439e-01 2.27990157e-01 3.03986134e-01 6.49904146e-01
 7.68813154e-02 6.26250662e-01 9.93690799e-01 9.57649378e-01
 7.14417476e-01 5.02702873e-01 6.41863410e-01 9.01068005e-02
 3.77829416e-01 3.14825554e-02 6.15021694e-01 8.27087474e-01
 5.57096781e-01 8.22179595e-01 8.13036934e-01 8.79986336e-01
 1.85448025e-01 4.73541962e-01 5.89765941e-01 8.39209083e-01
 2.98062022e-02 1.68016847e-01 9.43024868e-01 9.60299852e-01
 4.36120409e-02 7.97602479e-01 6.06760953e-01 5.50684102e-01
 2.89025219e-01 5.43729870e-01 6.20303222e-01 2.37303276e-01
 7.18208724e-01 2.69775997e-01 7.17484813e-02 7.19403019e-01
 4.94403280e-01 1.817665

In [14]:
#computing the avaerage of the array element
avg = np.mean(myArray)

In [15]:
#computing the vairance of the array element
vari = np.var(myArray)

In [16]:
#computing the standard deviation of the array element
std_dev =np.std(myArray)

In [18]:
#Printing results for average, variance and standard deviation
print("Average = ", avg)
print("Variance = ", vari)
print("Standard deviation = ", std_dev)

Average =  0.4808631206931005
Variance =  0.08153696337910049
Standard deviation =  0.2855467796685869


In [19]:
#Creating a 3x3 array
arr = np.array([[2,4,5],[8,10,12],[14,16,18]])

In [20]:
#Cumulative sum along the axis 0 (rows ) using the cumsum function
cumSum_rows = np.cumsum(arr, axis=0)

In [21]:
#Sum over rows for each of the 3 columns
sumRows = np.sum(arr, axis=0)

In [22]:
#Sum over columns for each of the 2 rows
sumCols = np.sum(arr, axis=1)

In [24]:
#Printing results
print("The original array is:\n", arr)
print("Cumulative sum along rows is:\n", cumSum_rows)
print("Sum over rows for each column:\n", sumRows)
print("Sum over column for each row:\n", sumCols)

The original array is:
 [[ 2  4  5]
 [ 8 10 12]
 [14 16 18]]
Cumulative sum along rows is:
 [[ 2  4  5]
 [10 14 17]
 [24 30 35]]
Sum over rows for each column:
 [24 30 35]
Sum over column for each row:
 [11 30 48]


In [25]:
#Defining the matrix
matrix1 = np.array([[2,4],[4,6]])
matrix2 = np.array([[3,1],[1,7]])

In [26]:
#Computing the matrix using the dot function
result = np.dot(matrix1,matrix2)

In [27]:
#printing the results
print(result)

[[10 30]
 [18 46]]
